# Generated by Django 5.2.2 on 2025-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0004_alter_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
